version: 3.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  # Display .NET Core version
  - cmd: nuget install
  - cmd: nuget restore azure-documentdb-odata-sql.sln
  # Display minimal restore text
  # - cmd: dotnet restore ./src/Lambda.NSubstituteHelper.sln --verbosity m --configfile src/NuGet.config
configuration: Release
build_script:
  - cmd: msbuild azure-documentdb-odata-sql.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: nuget pack azure-documentdb-odata-sql\azure-documentdb-odata-sql.nuspec -version %APPVEYOR_BUILD_VERSION%
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  #test
artifacts:
  - path: '**\lambda.azure.cosmosdb.odata.sql.*.nupkg'
nuget:
  account_feed: true
  project_feed: true
on_finish :
  # any cleanup in here
deploy: off
