name: Pull Request CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: "recursive"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'